### ISSUE TITLE
Last day of the month is not processed in bin/cron4dbs_condor

### ISSUE THREAD

**Issue by mrceyhun** [dmwm/CMSSpark#104]
`bin/cron4dbs_condor` does not process last day of months. It can be seen in `/cms/dbs_condor/release`. Since it is processing previous day's data and in each months starting to process current month, it is skipping last day of each month.

Probably a easy fix, opening this issue to not forget next week.

**Comment by mrceyhun** [comment]
catched by @kyrylogy

**Comment by kyrylogy** [comment]
I believe the issue lies [here](https://github.com/dmwm/CMSSpark/blob/103fbdd0224c93bbd7a410f3ff13bef7c2be4d03/bin/cron4dbs_condor#L19) and [here](https://github.com/dmwm/CMSSpark/blob/103fbdd0224c93bbd7a410f3ff13bef7c2be4d03/bin/cron4dbs_condor#L21)

tmpDirs=`hadoop fs -ls ${hdir}/$year/$month | grep tmp$ | awk '{print $8}' | sed -e "s,\.tmp,,g" -e "s,${hdir},,g"`
This gives us the date of .tmp file, which is the file of the day - on 1st of the month it would give _/2022/08/01_

lastSnapshot=`hadoop fs -ls ${hdir}/$year/$month | egrep -v ${pat} | tail -1 | awk '{print $8}'`
Here we get the same list of files, but without todays date. Then we take the path of last file - on 1st of the month it would pop the only available file. Additionally, we only apply it to current month's list of data, so there's no file behind the first file of current month.

I will fix it

**Comment by mrceyhun** [comment]
Thanks @kyrylogy , it would be great!

**Comment by mrceyhun** [comment]
Fixed by #109
